

version: "3.9"
services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"  # Внутри докера база запускается на порту 5432. Но на локальную машину "пробрасывается" на порт 5431
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}  # Проброшены сюда как переменные окружения. Для того, чтобы docker-compose их увидел,
      # нужно создать файл dotenv (.env)